config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'homes#index'
  get '/home', to: 'homes#index'

  devise_for :users
  resources :users, only: :show

  resources :skills
  resources :goals


  get 'texts/:id', to: 'texts#show'
  get 'twitters/index', to: 'twitters#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  require 'csv'
end

app/models/calc.rb
class Calc < ApplicationRecord
  def self.skill(user)
    user = user.joins(:skills).group(:email, :name).select(
    'email, name, sum(study_time) as study_time'
  )
  end

  def self.goal(user)
    user = user.joins(:goals).group(:email, :name).select(
      'email, name, target_time'
    )
  end

  def user_skill
    Skill.joins(:user).group(:email, :name).select('nickname, user_id, email, name, sum(study_time) as study_time')
  end
end

app/models/command.rb
class Command < ApplicationRecord
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
  validates :target_time, presence: true
  validates :name, uniqueness: true
end

app/models/import_csv.rb
class ImportCsv < ApplicationRecord
    def self.import(path)
        Text.delete_all
        list = []

        CSV.foreach(path, headers: true) do |row|
            list << {
                title: row["title"],
                contents: row["contents"],
                genre: row["genre"]
            }
        end

        puts "インポート処理を開始"
        begin
            Text.create!(list)
            puts "インポート完了!"
        rescue ActiveModel::UnknownAttributeError => invalid
            puts "インポートに失敗 : UnknownAttributeError"
        end
    end
end

app/models/import_csv2.rb
class ImportCsv2 < ApplicationRecord
  def self.import(path)
    CSV.foreach(path, headers: true) do |row|
      Command.create(
        title: row["title"],
        content: row["content"]
      )
    end
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user
  validates :study_time, presence: true

  def self.skills
    joins(:user).group(:email, :name).select('nickname, user_id, email, name, sum(study_time) as study_time')
  end

  def self.new_skill

  end
end

app/models/skill_list.rb
class SkillList < ApplicationRecord
end

app/models/text.rb
class Text < ApplicationRecord
end

app/models/twitter.rb
class Twitter < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :skills
  has_many :goals

  def self.user_skill
    joins(:skills).group(:email, :name).select(
      'email, name, sum(study_time) as study_time'
    )
  end

  def self.user_goal
    joins(:goals).group(:email, :name).select(
      'email, name, target_time'
    )
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def new
    @goal = Goal.new
  end

  def show
    @user = User.where(id: current_user)
    @skill = Skill.new
    @user_skills =
      @user.joins(:skills).group(:email, :name).select(
        'email, name, sum(study_time) as study_time'
      )
    @goal = Goal.new
    @user_goals =
      @user.joins(:goals).group(:email, :name).select(
        'email, name, target_time'
      )
  end

  def create
    Goal.create(
      name: skill_params[:name],
      target_time: skill_params[:target_time],
      user_id: current_user.id
    )
    redirect_to goal_path(current_user.id)
  end

  def skill_params
    params.require(:goal).permit(:name, :target_time)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @q = Text.ransack(params[:q])
    @texts = @q.result(distinct: true)
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  def show
    @commands = Command.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require "redcarpet"
  require "coderay"

  class HTMLwithCoderay < Redcarpet::Render::HTML
    def block_code(code, language)
      language = language.split(':')[0] if language.present?

      case language.to_s
      when 'rb'
        lang = 'ruby'
      when 'yml'
        lang = 'yml'
      when 'css'
        lang = 'css'
      when 'html'
        lang = 'html'
      when ''
        lang = 'md'
      else
        lang = language
      end

      CodeRay.scan(code, lang).div
    end
  end

  def markdown(text)
    html_render = HTMLwithCoderay.new(filter_html: true, hard_wrap: true)
    options = {
      autolink: true,
      space_after_headers: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      tables: true,
      hard_wrap: true,
      xhtml: true,
      lax_html_blocks: true,
      strikethrough: true
    }
    markdown = Redcarpet::Markdown.new(html_render, options)
    markdown.render(text)
  end

  def disp_twitter_text(**params)
    text =<<~EOS
    #{params[:now].name}を#{params[:now].study_time}時間勉強しました！

    合計#{params[:sum].sum(:study_time)}時間
    EOS
  end
end

app/helpers/goal_helper.rb
module GoalHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/twitters_helper.rb
module TwittersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
  <a class="navbar-brand" href="/">Skill-collection</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if user_signed_in? && current_user.admin? %>
        <li class="nav-item active">
          <a class="nav-item nav-link active" href="/admin" target="_blank=">管理画面</a>
        </li>
      <% end %>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "全ユーザーの学習記録", skills_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to "マイページ", user_path(current_user.id), class: 'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "ログイン", new_user_session_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to "新規登録", new_user_registration_path, class: 'nav-link active' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JointDev2</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/header' %>
  <div id="container">
    <section id="<%= "#{controller.controller_name}_#{controller.action_name}" %>">
      <%= yield %>
    </section>
  </div>
  <!---script群--->
  <script>
    $(document).ready(function () {
      $("#myInput").on("keyup", function () {
        var value = $(this).val().toLowerCase();
        $("#myTable tr").filter(function () {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
    });
  </script>
  <!---/script群--->
</body>
</html>